ExternalServicesLogin/Controllers/DBTestController.cs
using CAFIdentityManager.Models;
using CAFIdentityManager.Providers;
using ExternalServicesLogin.Models;
using ExternalServicesLogin.Providers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace ExternalServicesLogin.Controllers
{


    [Authorize]
    public class DBTestController : Controller
    {

        [Authorize]
        public ActionResult Index()
        {
            StringListModel model = new StringListModel();
            if (Request.IsAuthenticated)
            {
                var dbContext = new MCIADBContext();
                var users = dbContext.CAFUsers.ToList();

                model.ListOfString = new List<string>();
                foreach (var user in users)
                {
                    if (user != null && user.UserName != null)
                        model.ListOfString.Add(user.UserName);
                }
            }
            return View(model);
        }

        [Authorize(Roles = "Administrator")]
        public ContentResult AdminOnly()
        {
            return Content("For Admin Only");
        }

         [Authorize]
        public ActionResult EditUser(string username)
        {
            if (string.IsNullOrWhiteSpace(username))
            {
                return RedirectToAction("Index");
            }
            //var userManager = new CAFUserManager<CAFUser>(new CAFUserStore());
            var userStore = new CAFUserStore();
            var user = userStore.FindByNameAsync(username).Result;

            var dbContext = new MCIADBContext();
            var roles = dbContext.CAFRoles.ToList();

            UserWithRoles model = new UserWithRoles();
            model.UserInRole = new List<UserRoleModel>();
            model.Username = username;
            model.UserID = user.Id;

            if (user != null && roles != null && roles.Count() > 0)
            {
                foreach (var role in roles)
                {
                    bool result =  userStore.IsInRoleAsync(user, role).Result;
                    model.UserInRole.Add(new UserRoleModel()
                    {
                        RoleID = role.Id,
                        RoleName = role.Name,
                        ActionMethodName = result ? "RemoveUserRole" : "AddUserRole",
                        ActionName = result ? "Remove" : "Add",
                        IsInRole = result ? "YES" : "NO"
                    });
                }
            }
            return View(model);
        }

         [Authorize]
         public ActionResult RemoveUserRole(int userID, int roleID)
         {
             var cafUserStore = new CAFUserStore();

             var user = cafUserStore.FindByIdAsync(userID).Result;

             cafUserStore.RemoveFromRoleAsync(user, roleID);

             return RedirectToAction("Index");
         }


         [Authorize]
         public ActionResult AddUserRole(int userID, int roleID)
         {
             var cafUserStore = new CAFUserStore();

             var user = cafUserStore.FindByIdAsync(userID).Result;

             cafUserStore.AddToRoleAsync(user, roleID);

             return RedirectToAction("Index");
         }
    }
}

ExternalServicesLogin/Controllers/RoleController.cs
using CAFIdentityManager.Models;
using CAFIdentityManager.Providers;
using ExternalServicesLogin.Models;
using ExternalServicesLogin.Providers;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace ExternalServicesLogin.Controllers
{
    [Authorize]
    public class RoleController : Controller
    {
        public CAFRoleManager<CAFRole> roleManager { get; private set; }

        public RoleController()
        {
            roleManager = new CAFRoleManager<CAFRole>(new CAFRoleStore(new MCIADBContext()));
        }

        //
        // GET: /Role/
        public ActionResult Index()
        {
            StringListModel model = new StringListModel();
             
            var dbContext = new MCIADBContext();
            var items = dbContext.CAFRoles.ToList();

            model.ListOfString = new List<string>();
            foreach (var entry in items)
            {
                if (entry != null && entry.Name != null)
                    model.ListOfString.Add(entry.Name);
            }

            return View(model);
        }

        public ActionResult NewRole()
        {
            CAFRole role = new CAFRole();
            return View(role);
        }


        [HttpPost]
        public ActionResult NewRole(CAFRole model)
        {
           if(ModelState.IsValid)
           {
               roleManager.CreateAsync(model);       
           }
           return RedirectToAction("Index");
        }

        public ActionResult DeleteRole(string roleName)
        {
            var role = roleManager.FindByName(roleName);
            roleManager.DeleteAsync(role);
            return RedirectToAction("Index");
        }
    }
}

ExternalServicesLogin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("LoginApp", "Index", "Home", null, new { @class = "navbar-brand" })
                @Html.ActionLink("Users", "Index", "DBTest", null, new { @class = "navbar-brand" })
                @Html.ActionLink("Roles", "Index", "Role", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "HelpPage" }, null)</li>
                </ul>
            
                <ul class="nav navbar-nav navbar-right" data-bind="with: user">
                    <li>
                        <span class="navbar-text nofloat">Hello,
                        @HttpContext.Current.User.Identity.Name     </span>
                    </li>
                     
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("Scripts", required: false)
</body>
</html>